### ISSUE TITLE
not work!

### ISSUE THREAD

**Issue by xerron** [stardiviner/ob-php#1]
Execute src 

```org
#+BEGIN_SRC php
print 4 + 4;
#+END_SRC

#+RESULTS:
: print 4 + 4;
```

Ubuntu 16.04
Emacs 25.1
PHP 7 

I test: php -r "print 4 + 4;"  -> 8  ---> OK
but, emcas org-babel-execute-src-block -> :print 4 + 4 :-1:

**Comment by stardiviner** [comment]
@xerron confirmed. I will invested it later. Busy today.

**Comment by stardiviner** [comment]
@xerron I still can't find the way to fix this issue. Maybe you can ask question in Emacs.StackExchange.

**Comment by olymk2** [comment]
Same issue here with similar versions as above did any one find a fix ?

**Comment by stardiviner** [comment]
@olymk2 I will find time debug this issue. Maybe because Org-mode updated babel API functions recently.

**Comment by stardiviner** [comment]
@olymk2 @xerron I checked out, Using latest org-mode source code, it works fine. Seems Org-mode version issue. You need to edebug on `org-babel-execute:php`. and track down to essential org-mode Babel API functions. Provide me details.

**Comment by olymk2** [comment]
@stardiviner not sure how to do that, i used find function to find the code for =org-babel-execute:php= then tried using =edebug-on-entry= but it does not seem to trigger, never used edebug before so likely doing it wrong.

**Comment by olymk2** [comment]
some further info and possibly the cause, i tried putting in a message statement, this is its output;

    php return "1";

seems to be missing the -r that lead me down this route

```
#+BEGIN_SRC emacs-lisp
(mapconcat 'identity (list "php") " -r ")
#+END_SRC

#+RESULTS:
: php

#+BEGIN_SRC emacs-lisp
(mapconcat 'identity (list "php -r ") " -r ")
#+END_SRC

#+RESULTS:
: php -r 
```

so i am guessing the fact its missing he -r is to blame, but i can not explain why because of my lack of lisp knowledge.

**Comment by stardiviner** [comment]
@olymk2 Yes, you're right. That's the problem. I will update code to fix it.

**Comment by stardiviner** [comment]
@olymk2 Weird, I can't figure it how. I dive into source code, the option `-r` did caused this issue. And I have not idea how to fix it after many different tries.
I will remove `-r` option, it is original to avoid `<? .. ?>`. I will add declare of must use `<? ... ?>` in README.
If you have better solution. Please must let me know.

**Comment by stardiviner** [comment]
I pushed a commit which disable the `-r` option.

**Comment by olymk2** [comment]
I believe -r is correct, running 

    php "echo 1;"

where as 

    php -r "echo 1;"

works.

however trying a lisp block i don't get very far.

```
#+BEGIN_SRC emacs-lisp
    (org-babel-eval "php" "<?echo '1';?>")
#+END_SRC

#+RESULTS:
: <?echo '1';?>

#+BEGIN_SRC emacs-lisp
    (org-babel-eval "php -r " "echo '1';")
#+END_SRC

#+RESULTS:
#+begin_example
Usage: php [options] [-f] <file> [--] [args...]
   php [options] -r <code> [--] [args...]
   php [options] [-B <begin_code>] -R <code> [-E <end_code>] [--] [args...]
   php [options] [-B <begin_code>] -F <file> [-E <end_code>] [--] [args...]
   php [options] -S <addr>:<port> [-t docroot] [router]
   php [options] -- [args...]
   php [options] -a

  -a               Run interactively
  -c <path>|<file> Look for php.ini file in this directory
  -n               No configuration (ini) files will be used
  -d foo[=bar]     Define INI entry foo with value 'bar'
  -e               Generate extended information for debugger/profiler
  -f <file>        Parse and execute <file>.
  -h               This help
  -i               PHP information
  -l               Syntax check only (lint)
  -m               Show compiled in modules
  -r <code>        Run PHP <code> without using script tags <?..?>
  -B <begin_code>  Run PHP <begin_code> before processing input lines
  -R <code>        Run PHP <code> for every input line
  -F <file>        Parse and execute <file> for every input line
  -E <end_code>    Run PHP <end_code> after processing all input lines
  -H               Hide any passed arguments from external tools.
  -S <addr>:<port> Run with built-in web server.
  -t <docroot>     Specify document root <docroot> for built-in web server.
  -s               Output HTML syntax highlighted source.
  -v               Version number
  -w               Output source with stripped comments and whitespace.
  -z <file>        Load Zend extension <file>.

  args...          Arguments passed to script. Use -- args when first argument
                   starts with - or script is read from stdin

  --ini            Show configuration file names

  --rf <name>      Show information about function <name>.
  --rc <name>      Show information about class <name>.
  --re <name>      Show information about extension <name>.
  --rz <name>      Show information about Zend extension <name>.
  --ri <name>      Show configuration for extension <name>.

#+end_example

```

seems the code block is not being appended to the command in the right format, or i am doing something wrong, could be body param is not string.

**Comment by stardiviner** [comment]
Yes, you can print of the type of `body`, use function `type-of`.

**Comment by olymk2** [comment]
tried that the type was string, also found this which seems to do things a bit differently https://github.com/steckerhalter/ob-php.

noticed it looks like it reads from a buffer so perhaps -r is not correct anyway.

I also noticed it boils down to the below call, trying /bin/bash -c php -r "echo '1';" the command line did not seem to like that for some reason.
```
Debugger entered--entering a function:
* process-file("/bin/bash" "/tmp/babel-12806d-q/ob-input-12806gq1" (t "/tmp/babel-12806d-q/ob-error-12806S0E") nil "-c" "php")
  #[1028 "\304\305!\205\n
```

anyway  not sure there is much more digging i can do

**Comment by stardiviner** [comment]
Thanks, I'm looking it's source code. Actually I did found those existing `ob-php` variant projects before I create this simple `ob-php`. But I found they are not really good. So I created a simple one. But seems PHP programmer not active enough in Emacs community. That's why `ob-php` is not in Org-mode by default. And so many variants.

**Comment by stardiviner** [comment]
Fixed in this commit https://github.com/stardiviner/ob-php/commit/c281c1e17f0fd7de4adb6c3e6029dc2bd76beca1

**Comment by AlexFarran** [comment]
It still doesn't work for me. When I try to execute php code it just displays the php usage instructions. According to the php man page. php -r takes its input as a parameter, whereas php with no parameters takes its input from stdin.

**Comment by stardiviner** [comment]
@AlexFarran confirmed failed, I check out `ob-core.el` file git log. Have not found any related changes. I assume it's caused by a change in Org-mode core.

By running `php -r 'echo "hello, world";'` in command line. It works. So `php -r` is correct.
I hate to edebug on this again. very annoying. Can you edebug on function `org-babel-execute:php`, the following error function deeper.

**Comment by malsinet** [comment]
Hello @stardiviner, I have been trying this but I get the same results as @AlexFarran.

From my tests, `php -r` is not correct, because you are using `org-babel-eval` to run the code blocks, and what `org-babel-eval` does is saving the code to a temp file and then piping the contents of this file to the `php -r` command. So, your example would actually be executed as `echo 'echo "hello world";' | php -r`, which fails with the error @AlexFarran mentioned.

Using `php` with no parameters does not work either, the only thing that worked for me is `php -a`, but then it adds a line with "Interactive shell" and a blank line before the result of the executed code:

    echo 'date_default_timezone_set("UTC"); echo date("Y-m-d");' | php -a
    Interactive shell

    2017-11-20

**Comment by stardiviner** [comment]
I used to consider to integrate `inf-php`.  But Emacs don't have built-in `inf-php` support, and currently some options are now maintained for long time.
@malsinet You `php -a` option did works, but my output is like this:

```
#+begin_src shell
echo 'date_default_timezone_set("UTC"); echo date("Y-m-d");' | php -a
#+end_src

#+RESULTS:
: Interactive shell
: 
: php > date_default_timezone_set("UTC"); echo date("Y-m-d");
: 2017-11-21
: php > 
```
Obviously this can't be used, because block text output result might be input of other src blocks like literate programming with Org-mode.

**Comment by stardiviner** [comment]
I will suggest Emacs development to add `inf-php` support in Emacs.

**Comment by stardiviner** [comment]
Sorry for delay update.
I searched GitHub, found two inf-php implementations:
  - [X] https://github.com/emacsattic/inf-php
  - [X] https://github.com/taksatou/inf-php
They are same code.
Maybe you can add one of them to MELPA
Then I will try to let `ob-php` use `inf-php`.
I'm kind of busy recently, I will update here when I got news.
If someone want to implement it, PR welcome.

**Comment by malsinet** [comment]
I moved to using https://github.com/steckerhalter/ob-php, and since I do not use sessions, it mostly works fine, other than the fact that it is not available in MELPA and must be installed from github.

If I have some time I will give it a look, see if I can do it.

Thanks for the update

**Comment by stardiviner** [comment]
@malsinet I will the MELPA ob-php recipe to https://github.com/steckerhalter/ob-php. and I updated a new commit really fixed which my friend borrowed from https://github.com/steckerhalter/ob-php.
